<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/jupyter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
print(98+10-9.8)

98.2


In [ ]:
for i in range(5):
  print("SuperMAN")

SuperMAN
SuperMAN
SuperMAN
SuperMAN
SuperMAN


In [ ]:
s="A";
print(s)

A


In [ ]:
s="A";
print(chr(ord(s)+1))

B


In [ ]:
!pip install QuantumCircuit


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 101.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


In [ ]:
def s(a,b):
    return a+b;

In [ ]:
s(45,32)

77

In [ ]:
s(1237869,1236789)

2474658

In [ ]:
import pandas as np

In [ ]:
import numpy as np


In [ ]:
l=[1,2,3,4]
print(l)
type(l)

[1, 2, 3, 4]


list

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(a)
type(a)

[1 2 3 4 5 6 7 8 9 0]


numpy.ndarray

In [ ]:
for i in range(10):
  a[i]=a[i]+10
print(a)

[11 12 13 14 15 16 17 18 19 10]


In [ ]:
for i in range(10):
  print(a[i])

11
12
13
14
15
16
17
18
19
10


In [ ]:
print(a.shape)

(10,)


In [ ]:
b=[(1,2),(1,3),(3,4)]
print(b)

[(1, 2), (1, 3), (3, 4)]


In [ ]:
b.shape()

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
print(b.shape)

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
b=np.array[(1,2),(1,3),(3,4)]
print(b)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
x=np.zeros((5,5))
print(x)
x.dtype=int

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((2,2))
print(y)

[[1. 1.]
 [1. 1.]]


In [ ]:
z=np.twos((3,5))
print(z)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
z=np.full((3,2),44)
print(z)

[[44 44]
 [44 44]
 [44 44]]


In [ ]:
for i in range(3):
  for j in range(3):
    if i==j:
      s[i][j]=np.ones(1)
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


/tmp/ipykernel_183/2494825763.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  s[i][j]=np.ones(1)


In [ ]:
t=np.eye(5)

In [ ]:
for i in range(5):
  print(t[i]+99)

[100.  99.  99.  99.  99.]
[ 99. 100.  99.  99.  99.]
[ 99.  99. 100.  99.  99.]
[ 99.  99.  99. 100.  99.]
[ 99.  99.  99.  99. 100.]


In [ ]:
t1=np.random.random((3,3))
print(t1)

[[0.04107199 0.23724966 0.58520326]
 [0.99149941 0.86677265 0.20989304]
 [0.98933399 0.80344639 0.8610527 ]]


In [ ]:
t1=np.random.randint(13,200,(3,3))
print(t1)

[[117 172  55]
 [196  81  29]
 [173  23  29]]


In [ ]:
d=np.linspace(3,15,(3,3))
print(d)

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
e=np.arange(3,10,1)

In [ ]:
print(e)

[3 4 5 6 7 8 9]


In [ ]:
e=np.arange(3,10,9)
print(e)

[3]


In [ ]:
list=([1,2,34,4,35,2],[2,3,4,5,6,7],[23,13,537,74,345,8])
a=np.asarray(list)


In [ ]:
print(a)

[[  1   2  34   4  35   2]
 [  2   3   4   5   6   7]
 [ 23  13 537  74 345   8]]


In [ ]:
print(a.shape)

(3, 6)


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.size)

18


In [1]:
list=1,2,3,4,5,6,7,8
list2=4,2,4,2

In [3]:
print(list+list2)#concatenation

(1, 2, 3, 4, 5, 6, 7, 8, 4, 2, 4, 2)


In [10]:
import numpy as np
a=np.random.randint(1,20,(3,3))
b=np.random.randint(1,20,(3,3))
print(a)
print(b)

[[ 3  6  1]
 [17 14  5]
 [11  8 10]]
[[17  7 19]
 [ 9 13 18]
 [14  7 10]]


In [11]:
print(a+b)

[[20 13 20]
 [26 27 23]
 [25 15 20]]


In [ ]:
print(a-b)
print(a*b)