<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/video15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
  import numpy as np
l=[1,2,3,4,5,6]
a=np.array(l)
print(a)

[1 2 3 4 5 6]


In [ ]:
a.shape

(6,)

In [ ]:
b=np.array([(1,2,3),(4,5,6)])
b.shape

(2, 3)

In [ ]:
x=np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [ ]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
q=np.full((3,3),'s')
print(q)

[['s' 's' 's']
 ['s' 's' 's']
 ['s' 's' 's']]


In [ ]:
p=np.eye(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
b=np.random.random((3,3))
print(b)

[[0.35810151 0.78781585 0.66484493]
 [0.07002466 0.13067916 0.44303399]
 [0.24530447 0.64194581 0.47615232]]


In [4]:
z=np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [10]:
i=np.random.randint(3,400,(3,4))
print(i)

[[294 141 201 155]
 [279  49 358 100]
 [ 19  71 349 309]]


In [15]:
d=np.linspace(1,120,20)
print(d)

[  1.           7.26315789  13.52631579  19.78947368  26.05263158
  32.31578947  38.57894737  44.84210526  51.10526316  57.36842105
  63.63157895  69.89473684  76.15789474  82.42105263  88.68421053
  94.94736842 101.21052632 107.47368421 113.73684211 120.        ]
