<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/video5254_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
matrix2=np.array([[1,2,3],[3,2,2],[6,7,2]])
m=matrix+matrix2
m

array([[ 2,  4,  6],
       [ 7,  7,  8],
       [13, 15, 11]])

In [5]:
matrix.shape

(3, 3)

In [9]:
random=np.random.rand(3,3)
random

array([[0.71550879, 0.81653829, 0.37270137],
       [0.29883116, 0.89485952, 0.98568962],
       [0.0058469 , 0.49175662, 0.18238519]])

In [10]:
r=np.random.randint(100,size=(3,3))
r

array([[11, 62, 61],
       [27, 96, 13],
       [ 9, 63, 30]])

In [14]:
r1=np.ones((3,3))
r1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
r2=np.zeros((4,5))
r2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
rx=np.random.randint(100,size=(4,5))
rx

array([[31, 20, 69, 55, 43],
       [15, 96, 92, 14, 25],
       [ 9, 76, 64, 21, 17],
       [19, 89, 64, 51, 88]])

In [22]:
rx.T

array([[31, 15,  9, 19],
       [20, 96, 76, 89],
       [69, 92, 64, 64],
       [55, 14, 21, 51],
       [43, 25, 17, 88]])

In [23]:
rx.shape

(4, 5)

In [24]:
rx.T.shape

(5, 4)

In [25]:
import numpy as np

In [26]:
ry=np.random.randint(100,size=(4,5))

In [27]:
np.add(rx,ry)

array([[111,  33, 128,  76,  45],
       [ 23, 188, 122,  17,  52],
       [ 88, 133,  83,  58,  62],
       [ 55, 150, 119,  89, 178]])

In [28]:
np.subtract(rx,ry)

array([[-49,   7,  10,  34,  41],
       [  7,   4,  62,  11,  -2],
       [-70,  19,  45, -16, -28],
       [-17,  28,   9,  13,  -2]])

In [29]:
np.multiply(3,rx)

array([[ 93,  60, 207, 165, 129],
       [ 45, 288, 276,  42,  75],
       [ 27, 228, 192,  63,  51],
       [ 57, 267, 192, 153, 264]])

In [31]:
np.dot(rx,rx.T)

array([[10996, 10578,  8101, 13374],
       [10578, 18726, 14038, 17631],
       [ 8101, 14038, 10683, 13598],
       [13374, 17631, 13598, 22723]])