<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/video15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l=[1,2,3,4,5,6]
a=np.array(l)
print(a)

[1 2 3 4 5 6]


In [ ]:
a.shape

(6,)

In [ ]:
b=np.array([(1,2,3),(4,5,6)])
b.shape

(2, 3)

In [8]:
x=np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [10]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
q=np.full((3,3),'s')
print(q)

[['s' 's' 's']
 ['s' 's' 's']
 ['s' 's' 's']]


In [22]:
p=np.eye(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
