<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/video15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
  import numpy as np
l=[1,2,3,4,5,6]
a=np.array(l)
print(a)

[1 2 3 4 5 6]


In [ ]:
a.shape

(6,)

In [ ]:
b=np.array([(1,2,3),(4,5,6)])
b.shape

(2, 3)

In [ ]:
x=np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [ ]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
q=np.full((3,3),'s')
print(q)

[['s' 's' 's']
 ['s' 's' 's']
 ['s' 's' 's']]


In [ ]:
p=np.eye(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
b=np.random.random((3,3))
print(b)

[[0.35810151 0.78781585 0.66484493]
 [0.07002466 0.13067916 0.44303399]
 [0.24530447 0.64194581 0.47615232]]


In [4]:
z=np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [10]:
i=np.random.randint(3,400,(3,4))
print(i)

[[294 141 201 155]
 [279  49 358 100]
 [ 19  71 349 309]]


In [15]:
d=np.linspace(1,120,20)
print(d)

[  1.           7.26315789  13.52631579  19.78947368  26.05263158
  32.31578947  38.57894737  44.84210526  51.10526316  57.36842105
  63.63157895  69.89473684  76.15789474  82.42105263  88.68421053
  94.94736842 101.21052632 107.47368421 113.73684211 120.        ]


In [19]:
q=[23,23,231,123,213]
q1=np.asarray(q)
print(q1)
type(q1)

[ 23  23 231 123 213]


numpy.ndarray

In [20]:
q=[23,23,231,123,213]
q1=np.array(q)
print(q1)
type(q1)

[ 23  23 231 123 213]


numpy.ndarray

In [21]:
q2=np.random.randint(1,100,(3,4))
print(q2)

[[10 31 40 15]
 [74 67 12 62]
 [81 34 28 40]]


In [22]:
print(q2.shape)

(3, 4)


In [23]:
print(q2.ndim)

2


In [24]:
q2.size

12

In [26]:

q=np.random.randint(1,20,(3,4))
print(q)

[[14 17 11  3]
 [ 4  9  7 15]
 [13  3  4  3]]


In [27]:
q.size

12

In [28]:
q.ndim

2

In [29]:
q.shape

(3, 4)

In [30]:
q.dtype

dtype('int64')

In [31]:
s=np.random.randint(1,30,(3,4))
s

array([[ 7, 12, 22, 12],
       [ 3, 22,  1,  5],
       [ 8, 11, 29, 21]])

In [32]:
print(q+s)

[[21 29 33 15]
 [ 7 31  8 20]
 [21 14 33 24]]


In [33]:
print(q*s)

[[ 98 204 242  36]
 [ 12 198   7  75]
 [104  33 116  63]]


In [34]:
q.T

array([[14,  4, 13],
       [17,  9,  3],
       [11,  7,  4],
       [ 3, 15,  3]])

In [36]:
(q*s).T

array([[ 98,  12, 104],
       [204, 198,  33],
       [242,   7, 116],
       [ 36,  75,  63]])

In [42]:
p=q.reshape(4,3)
print(p)

[[14 17 11]
 [ 3  4  9]
 [ 7 15 13]
 [ 3  4  3]]
